# Variables
@baseUrl = http://localhost:3333

# Create account
# @name createAccounts
POST {{baseUrl}}/accounts
Accept: application/json
Content-Type: application/json

# {
# 	"name": "Test room",
#   "description": "This is a test"
# }

