# Variables
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# Create account
# @name create_account
POST {{baseUrl}}/accounts
Accept: application/json
Content-Type: application/json

{
	"name": "Test room",
  "email": "email@l.com",
  "password": "password"
}
###

# Authenticate
# @name authenticate
POST {{baseUrl}}/sessions
Accept: application/json
Content-Type: application/json

{
  "email": "email@l.com",
  "password": "password"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Test question",
  "content": "This is a test question"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1&pageSize=10
Content-Type: application/json
Authorization: Bearer {{authToken}}


