# Variables
@baseUrl = http://localhost:3333

# Create account
# @name createAccounts
POST {{baseUrl}}/accounts
Accept: application/json
Content-Type: application/json

{
	"name": "Test room",
  "email": "test@l.com",
  "password": "test12345"
}
###

# Authenticate
# @name auth
POST {{baseUrl}}/sessions
Accept: application/json
Content-Type: application/json

{
  "email": "test@l.com",
  "password": "test1235"
}

